name: TEC
channels:
  - defaults
dependencies:
  - alabaster=0.7.12
  - argh=0.26.2
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - astropy=4.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - bcrypt=3.1.7
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.1
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cloudpickle=1.2.2
  - colorama=0.4.3
  - cryptography=2.8
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - entrypoints=0.3
  - flake8=3.7.9
  - freetype=2.9.1
  - future=0.18.2
  - geos=3.7.1
  - hypothesis=5.4.1
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=2.8
  - imagesize=1.2.0
  - importlib_metadata=1.4.0
  - intel-openmp=2019.4
  - intervaltree=3.0.2
  - ipykernel=5.1.4
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.14.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - keyring=20.0.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.3
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - libspatialindex=1.9.3
  - libtiff=4.1.0
  - libxml2=2.9.9
  - libxslt=1.1.33
  - lxml=4.4.2
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - numpy=1.18.1
  - numpy-base=1.18.1
  - numpydoc=0.9.2
  - olefile=0.46
  - openssl=1.1.1d
  - owslib=0.18.0
  - packaging=20.1
  - pandas=1.0.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - paramiko=2.6.0
  - parso=0.6.0
  - pathtools=0.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pluggy=0.13.1
  - proj4=5.2.0
  - prompt_toolkit=3.0.2
  - psutil=5.6.7
  - py=1.8.1
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pydocstyle=4.0.1
  - pyepsg=0.4.0
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pykdtree=1.3.1
  - pylint=2.4.4
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pyshp=2.1.0
  - pysocks=1.7.1
  - pytest=5.3.5
  - pytest-arraydiff=0.3
  - pytest-astropy=0.7.0
  - pytest-astropy-header=0.1.2
  - pytest-doctestplus=0.5.0
  - pytest-openfiles=0.4.0
  - pytest-remotedata=0.3.2
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.2
  - python-language-server=0.31.2
  - pytz=2019.3
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pyyaml=5.2
  - pyzmq=18.1.0
  - qdarkstyle=2.8
  - qt=5.9.7
  - qtawesome=0.6.0
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - requests=2.22.0
  - rope=0.16.0
  - rtree=0.8.3
  - scipy=1.3.2
  - setuptools=45.1.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.1.0
  - sphinx=2.3.1
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - spyder=4.0.1
  - spyder-kernels=1.8.1
  - sqlite=3.30.1
  - testpath=0.4.4
  - tk=8.6.8
  - traitlets=4.3.3
  - ujson=1.35
  - urllib3=1.25.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - watchdog=0.9.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.1.7
  - yapf=0.28.0
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - aacgmv2==2.6.0
    - altair==4.0.1
    - astor==0.8.1
    - base58==2.0.0
    - blinker==1.4
    - boto3==1.12.30
    - botocore==1.15.30
    - cachetools==4.0.0
    - click==7.1.1
    - docutils==0.15.2
    - enum-compat==0.0.3
    - geomagindices==1.2.6
    - h5py==2.10.0
    - ipywidgets==7.5.1
    - jmespath==0.9.5
    - madrigalweb==3.1.12
    - meson==0.53.1
    - msise00==1.7.1
    - ninja==1.9.0.post1
    - notebook==6.0.3
    - prometheus-client==0.7.1
    - protobuf==3.11.3
    - pydeck==0.3.0b2
    - pyigrf==0.3.1
    - pywinpty==0.5.7
    - s3transfer==0.3.3
    - send2trash==1.5.0
    - streamlit==0.57.0
    - terminado==0.8.3
    - toml==0.10.0
    - toolz==0.10.0
    - tornado==5.1.1
    - tzlocal==2.0.0
    - validators==0.14.2
    - widgetsnbextension==3.5.1
    - xarray==0.15.0

